version: '3'

services:
  app:
    build:
      context: .
    volumes:
      - .:/home/app
      - adaptaviz_node_modules:/home/app/node_modules
    ports:
      - 3000:3000

volumes:
  adaptaviz_node_modules: