name: Deploy to scaleway.


# Run workflow on every push to master branch.
on:
  push:
    branches: [main]

jobs:
  deploy_scw:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: 'arm64'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: rg.fr-par.scw.cloud/my-services
          username: nologin
          password: ${{ secrets.SCW_SECRET_KEY }}

      # Build the images
      - name: Build and push docker
        uses: docker/build-push-action@v5
        with:
          push: true
          file: ./Dockerfile.prod
          tags: rg.fr-par.scw.cloud/my-services/adaptaviz-fr:latest
          platforms: linux/arm64
          cache-from: type=gha,mode=max
          cache-to: type=gha,mode=max
