name: Lint

on: ['pull_request']
jobs:
  js-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependecies
        run: yarn install --immutable --immutable-cache --check-cache

      - name: Run ESLint
        run: yarn run lint